"""skos.brain.index — Per-namespace INDEX format.

"Indexing is the single most important part" — Infinite Brain framework.

With thousands of entity nodes, an agent cannot fit the whole brain in one
prompt.  The solution: a ``_index.md`` per namespace listing each entity with
its one-line summary, so the agent scans the index first and drills into only
the nodes it needs.

Index file location:
    <wiki_root>/pages/entities/<namespace>/_index.md

Format:
    ---
    namespace: <namespace>
    entity_count: N
    updated: <ISO-date>
    ---
    # <namespace> — entity index

    | id | type | lifecycle | summary |
    |----|------|-----------|---------|
    | agent-foo | agent | canon | Does X for Y. |
    ...

Public API:
    build_index(namespace_dir)  — scan *.md, write _index.md, return path
    read_index(namespace_dir)   — parse _index.md → list[IndexEntry]
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

from skos.brain.entity import parse, ParseError


@dataclass
class IndexEntry:
    """One row in a namespace index."""
    id: str
    entity_type: str
    lifecycle_state: str
    summary: str
    slug: str  # filename without .md


def build_index(namespace_dir: str | Path) -> Path:
    """Scan all entity *.md files in *namespace_dir* and write/overwrite ``_index.md``.

    Files named ``_index.md`` are ignored (not re-indexed).
    Unparseable files are silently skipped (logged to stderr).

    Returns:
        Path to the written ``_index.md``.
    """
    ns_path = Path(namespace_dir)
    if not ns_path.is_dir():
        raise FileNotFoundError(f"Namespace directory not found: {ns_path}")

    entries: list[IndexEntry] = []
    for md_file in sorted(ns_path.glob("*.md")):
        if md_file.name.startswith("_"):
            continue
        try:
            node = parse(md_file.read_text(encoding="utf-8"))
        except ParseError:
            import sys
            print(f"[brain.index] skipping unparseable file: {md_file.name}", file=sys.stderr)
            continue
        entries.append(IndexEntry(
            id=node.id,
            entity_type=node.type,
            lifecycle_state=node.lifecycle_state,
            summary=node.summary,
            slug=md_file.stem,
        ))

    namespace = ns_path.name
    today = date.today().isoformat()

    lines: list[str] = [
        "---",
        f"namespace: {namespace}",
        f"entity_count: {len(entries)}",
        f"updated: {today}",
        "---",
        f"",
        f"# {namespace} — entity index",
        f"",
        f"> Auto-generated by `skos brain index`. Do not edit by hand — re-run to refresh.",
        f"> Scan this file first; open individual nodes only when you need the body.",
        f"",
        f"| id | type | lifecycle | summary |",
        f"|----|------|-----------|---------|",
    ]
    for e in entries:
        summary_escaped = e.summary.replace("|", "\\|")
        lines.append(f"| {e.id} | {e.entity_type} | {e.lifecycle_state} | {summary_escaped} |")

    index_path = ns_path / "_index.md"
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return index_path


def read_index(namespace_dir: str | Path) -> list[IndexEntry]:
    """Parse an existing ``_index.md`` and return a list of IndexEntry objects.

    Returns an empty list if ``_index.md`` does not exist.
    """
    ns_path = Path(namespace_dir)
    index_path = ns_path / "_index.md"
    if not index_path.exists():
        return []

    entries: list[IndexEntry] = []
    in_table = False
    for line in index_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("| id |") or stripped.startswith("|----"):
            in_table = True
            continue
        if in_table and stripped.startswith("|") and stripped.endswith("|"):
            parts = [p.strip() for p in stripped.strip("|").split("|")]
            if len(parts) >= 4:
                entries.append(IndexEntry(
                    id=parts[0],
                    entity_type=parts[1],
                    lifecycle_state=parts[2],
                    summary=parts[3].replace("\\|", "|"),
                    slug=parts[0],  # id is used as slug fallback
                ))
    return entries
